//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PAID_PROJECT_02_DBEntities : DbContext
    {
        public PAID_PROJECT_02_DBEntities()
            : base("name=PAID_PROJECT_02_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sch_Attendance> Sch_Attendance { get; set; }
        public virtual DbSet<Sch_Classes> Sch_Classes { get; set; }
        public virtual DbSet<Sch_Courses> Sch_Courses { get; set; }
        public virtual DbSet<Sch_Departments> Sch_Departments { get; set; }
        public virtual DbSet<Sch_Inventory> Sch_Inventory { get; set; }
        public virtual DbSet<Sch_Students> Sch_Students { get; set; }
        public virtual DbSet<Sch_Textbooks> Sch_Textbooks { get; set; }
    }
}
