//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sch_Inventory
    {
        public int Id { get; set; }
        public Nullable<int> ResourceId { get; set; }
        public string ResourceName { get; set; }
        public Nullable<bool> InStock { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Rack { get; set; }
        public string Shelf { get; set; }
        public string Condition { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
